- apt_key: keyserver=hkp://keyserver.ubuntu.com id=561F9B9CAC40B2F7

- apt_repository: repo='deb https://oss-binaries.phusionpassenger.com/apt/passenger trusty main' state=present

- apt: update_cache=yes

- name: install packages
  apt: name={{ item }} state=present
  with_items:
    - git
    - nodejs
    - npm
    - apt-transport-https
    - ca-certificates
    - nginx-extras
    - passenger

- name: install application specific packages
  apt: name={{ item }} state=present
  with_items: extra_packages


- lineinfile: dest=/etc/nginx/nginx.conf regexp="passenger_root" line="passenger_root /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini;"

- template: src=default.j2 dest=/etc/nginx/sites-enabled/default
  notify:
    - reload nginx

- git: repo="{{ app_git_url }}" dest=/var/www/nodejs
  tags: deploy
  notify:
    - reload nginx

- service: name=nginx state=restarted
